apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      containers:
      - name: demo-java
        image: thuanlv/demo-java:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://alloy-gateway.monitor.svc:4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_SERVICE_NAME
          value: demo-java
